route:
  receiver: "slack"

receivers:
  - name: "slack"
    slack_configs:
      - send_resolved: true
        username: "Prometheus"
        channel: "#general"
        api_url: "https://hooks.slack.com/services/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"
